### ISSUE TITLE
Looking forward to your code

### ISSUE THREAD

**Issue by WkangLiu** [mczhuge/CubeNet#2]
Looking forward to your code

**Comment by mczhuge** [comment]
Sorry, this project was completed three years ago. And after 1 year following my graduation, this paper was accepted.


The initial plan is to construct a model **without** all tricky modules, including ASPP, attention, and CRF. Experiments indicate that multi-level connection can achieve SOTA performance in COD tasks without the use of cumbersome mechanisms.

Here is two basic ideas and pseudocode,

## 1. X-shape connection
```
def x_connect(in1=None, in2, in3=None):

    if in1 == None:
        in1 = in2
    if in3 == None:
        in3 = in2

    in1 = CBR(in1)  #CBR is the layer consists of Conv3X3, BatchNorm and ReLU
    in2 = CBR(in2)
    in3 = CBR(in3)

    if in1.size != in3.size:
        reshape(in1, in2) # make in1 like in2
    if in3.size != in2.size:
        reshape(in3, in2) # make in3 like in2
    
    mid_fuse = in1 * in2 * in3 # this should split into 2 steps to conduct
    mid_fuse = CBR(mid_fuse)

    in1_ = CBR(in1 + mid_fuse)
    in2_ =  CBR(in2+mid_fuse)
    in3_ =  CBR(in3+mid_fuse)

   return in1_, in2_, in3_
```

## 2. Edge Supervision
You could refer [here](https://github.com/mczhuge/ICON/blob/main/main/train.py#37) which is originated from [F3Net](https://arxiv.org/abs/1911.11445).

Apologies for missing the code again, but you can easily implement this code by making a small modification to the [ICON](https://github.com/mczhuge/ICON) project.

**Comment by WkangLiu** [comment]
Thank you！
The Edge Supervision module solves my problem

**Comment by dante1024** [comment]
> 

Could you please write a pseudo code for the concat mode?
